version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taxi_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: taxi_weather
    ports:
      - "5432:5432"
    volumes:
      - ./models/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: